import numpy as np
from sklearn.linear_model import LogisticRegression
import json

# Generate Synthetic Tabular Data for the Model
# Features: [BPM, SpO2]
# Target: 0 (Low), 1 (Elevated), 2 (High Risk)
np.random.seed(42)

X = []
y = []

# Class 0: Low Risk (BPM: 60-100, SpO2: 95-100)
for _ in range(400):
    bpm = np.random.uniform(60, 100)
    spo2 = np.random.uniform(95, 100)
    X.append([bpm, spo2])
    y.append(0)

# Class 1: Elevated Risk (BPM: 50-60 or 100-115, SpO2: 90-95)
for _ in range(300):
    if np.random.rand() > 0.5:
        bpm = np.random.uniform(100, 115)
    else:
        bpm = np.random.uniform(55, 60)
    spo2 = np.random.uniform(90, 95)
    X.append([bpm, spo2])
    y.append(1)

# Class 2: High Risk (BPM > 115 or < 55, SpO2 < 90)
for _ in range(300):
    if np.random.rand() > 0.5:
        bpm = np.random.uniform(115, 180)
    else:
        bpm = np.random.uniform(30, 55)
    spo2 = np.random.uniform(70, 90)
    X.append([bpm, spo2])
    y.append(2)

X = np.array(X)
y = np.array(y)

# We normalize the features first for stability
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_norm = (X - X_mean) / X_std

# Train AI Model
model = LogisticRegression(solver='lbfgs', max_iter=1000)
model.fit(X_norm, y)

# Extract learned Matrices
W = model.coef_
b = model.intercept_

js_code = f"""
// ----------------------------------------------------
// AUTO-GENERATED BY ML MODEL PIPELINE
// Pretrained AI Risk Classification Model (Logistic Reg)
// Features: [BPM, SpO2]
// ----------------------------------------------------

class RiskPredictor {{
    static mean = {X_mean.tolist()};
    static std = {X_std.tolist()};
    static weights = {W.tolist()};
    static bias = {b.tolist()};

    // Performs forward pass matrix multiplication
    static predict(bpm, spo2) {{
        // Z-score Normalization
        const features = [
            (bpm - this.mean[0]) / (this.std[0] || 1),
            (spo2 - this.mean[1]) / (this.std[1] || 1)
        ];

        let logits = [0, 0, 0];
        
        // Z = W * X + b
        for (let classIdx = 0; classIdx < 3; classIdx++) {{
            let logit = this.bias[classIdx];
            for (let fIdx = 0; fIdx < 2; fIdx++) {{
                logit += features[fIdx] * this.weights[classIdx][fIdx];
            }}
            logits[classIdx] = logit;
        }}

        // ArgMax extraction
        let maxIndex = 0;
        let maxValue = logits[0];
        for (let i = 1; i < 3; i++) {{
            if (logits[i] > maxValue) {{
                maxValue = logits[i];
                maxIndex = i;
            }}
        }}

        const labels = ['Low Risk', 'Elevated Risk', 'High Risk'];
        return {{
            riskLevel: maxIndex, // 0, 1, 2
            riskLabel: labels[maxIndex]
        }};
    }}
}}

export default RiskPredictor;
"""

print(js_code)
