// ----------------------------------------------------
// AUTO-GENERATED BY ML MODEL PIPELINE
// Pretrained AI Risk Classification Model (Logistic Reg)
// Features: [BPM, SpO2]
// ----------------------------------------------------

class RiskPredictor {
    static mean = [84.03165799053204, 90.88902169722235];
    static std = [33.555022239374466, 7.933200644741947];
    static weights = [[-0.2460702438747364, 8.835791103895433], [0.09420013883642259, -0.8872445004923388], [0.15187010503831455, -7.9485466034030905]];
    static bias = [-2.6552758009966237, 2.2136326862130953, 0.4416431147835098];

    // Performs forward pass matrix multiplication
    static predict(bpm, spo2) {
        // Z-score Normalization
        const features = [
            (bpm - this.mean[0]) / (this.std[0] || 1),
            (spo2 - this.mean[1]) / (this.std[1] || 1)
        ];

        let logits = [0, 0, 0];
        
        // Z = W * X + b
        for (let classIdx = 0; classIdx < 3; classIdx++) {
            let logit = this.bias[classIdx];
            for (let fIdx = 0; fIdx < 2; fIdx++) {
                logit += features[fIdx] * this.weights[classIdx][fIdx];
            }
            logits[classIdx] = logit;
        }

        // ArgMax extraction
        let maxIndex = 0;
        let maxValue = logits[0];
        for (let i = 1; i < 3; i++) {
            if (logits[i] > maxValue) {
                maxValue = logits[i];
                maxIndex = i;
            }
        }

        const labels = ['Low Risk', 'Elevated Risk', 'High Risk'];
        return {
            riskLevel: maxIndex, // 0, 1, 2
            riskLabel: labels[maxIndex]
        };
    }
}

export default RiskPredictor;
